### ISSUE TITLE
`'*'` gets parsed as `tag`

### ISSUE THREAD

**Issue by T-727** [neovim/tree-sitter-vimdoc#105]
## Problem
`'*'` gets a parsed as a `tag` node
### Examples
- `editing.txt` line 1584
- `autocmd.txt` line 1165
#### Additional notes
Reproducable on Windows11, nvim release `0.9.0` with `nvim --clean`

**Comment by clason** [comment]
That is known and "wontfix" -- the docs should be edited instead to use the unambiguous `"*"`. (PR welcome.)

**Comment by justinmk** [comment]
Incidentally, this is mostly fixed in https://github.com/neovim/tree-sitter-vimdoc/pull/97 (`'*'` will parse as `word` and possibly `ERROR`, though I'll try to improve that). 

But still, it's silly for help text to have invalid links like this. `'` is a special char in help text, it shouldn't be mis-used.
