### ISSUE TITLE
two lines are combined as one: options.txt

### ISSUE THREAD

**Issue by jdhao** [neovim/tree-sitter-vimdoc#50]
Context:

```
If you want to include a ':' in a set command precede it with a '\'.  The
backslash in front of the ':' will be removed.  Example:
```

The code block below are combined with the line following it (`This sets the 'fillchars' option`). 

Also in context for option `filetype`

```
When a dot appears in the value then this separates two filetype
	names.  Example:
```

Same issue.

**Comment by justinmk** [comment]
context is:

```
If you want to include a ':' in a set command precede it with a '\'.  The
backslash in front of the ':' will be removed.  Example:
   /* vi:set fillchars=stl\:^,vert\:\|: */ ~
This sets the 'fillchars' option to "stl:^,vert:\|".  Only a single backslash
before the ':' is removed.  Thus to include "\:" you have to specify "\\:".
```

Problem is that `column_heading` children are `$._atom` instead of plaintext words, so the `*/` is parsed as an unclosed tag. https://github.com/neovim/tree-sitter-vimdoc#known-issues

For these cases in option.txt, there's no reason they should be column_heading so I will change them to codeblocks.
