### ISSUE TITLE
parse error: options.txt 

### ISSUE THREAD

**Issue by jdhao** [neovim/tree-sitter-vimdoc#51]
Found `tree-sitter-vimdoc` parse error at: https://neovim.io/doc/user/options.html

Context:

```
	to check what is following.  E.g. for Javascript, if a function is
	defined with "func_name = function(args)": >
		^\s*\ze\i\+\s*=\s*function(
<	If the function is defined with "func_name : function() {...": >
	        ^\s*\ze\i\+\s*[:]\s*(*function\s*(
<	When using the ":set" command, you need to double the backslashes!
	To avoid that use `:let` with a single quote string: >
```

The 3rd code block is not rendered correctly as code block.

**Comment by justinmk** [comment]
> The 3rd code block is not rendered correctly as code block.

The unclosed `{` causes an error. Because `{...}` can contain spaces. For authoring Vim help, if syntax like `{`, `*`, and `|` are to mean anything at all (and give useful errors), then sometimes errors really need to be errors :) 

So the fix here is to fix this help section. Alternatively, we could introduce a `(quote)` form that captures things with quotes `"..."`.
